version: '3.9'

services:
  pdf_processing_service_qa_mode:
    image: 064427434392.dkr.ecr.us-east-1.amazonaws.com/pdf_processing_service:latest
    container_name: pdf_processing_service_qa_mode
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=PRODUCTION
    env_file:
      - .env
      - src_env/prod/.env
    ports:
      - '${PROD_QA_SYSTEM_APP_PORT}:${PROD_QA_APP_PORT}/tcp'
    expose:
      - '${PROD_QA_APP_PORT}/tcp'
    command: gunicorn main:app --worker-tmp-dir /dev/shm -b ${PROD_QA_APP_HOST}:${PROD_QA_APP_PORT} -w ${PROD_QA_APP_WORKERS} -t ${PROD_QA_APP_TIMEOUT} --graceful-timeout ${PROD_QA_APP_GRACEFUL_TIMEOUT} -k uvicorn.workers.UvicornWorker
